// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBk4Cw1IM6FB8R6jsiWMc4Sxh9BRXPjMmk',
    appId: '1:42648457098:web:7907bb1b006bd00cdd4273',
    messagingSenderId: '42648457098',
    projectId: 'todo-app-fab95',
    authDomain: 'todo-app-fab95.firebaseapp.com',
    storageBucket: 'todo-app-fab95.appspot.com',
    measurementId: 'G-K4GT17BWGZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCCkFHEkGieuq5x5ZdVHKDOwers3XDXIsg',
    appId: '1:42648457098:android:26bd731ae871a51add4273',
    messagingSenderId: '42648457098',
    projectId: 'todo-app-fab95',
    storageBucket: 'todo-app-fab95.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCXbcdZyvKP4qPzFQPNFH2S7Zs23twa-1w',
    appId: '1:42648457098:ios:e1c9a7967c547762dd4273',
    messagingSenderId: '42648457098',
    projectId: 'todo-app-fab95',
    storageBucket: 'todo-app-fab95.appspot.com',
    iosBundleId: 'com.example.todo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCXbcdZyvKP4qPzFQPNFH2S7Zs23twa-1w',
    appId: '1:42648457098:ios:2693e4e4c36b9276dd4273',
    messagingSenderId: '42648457098',
    projectId: 'todo-app-fab95',
    storageBucket: 'todo-app-fab95.appspot.com',
    iosBundleId: 'com.example.todo.RunnerTests',
  );
}
